### PR TITLE
Save output parameters to a file

### PR DESCRIPTION
**Pull request by jbeezley**
This detects if there are any output parameters (other than files) and adds a new panel asking for a place to store the output parameter file.  With the PositivePixelCount cli, the panel appears and the information is passed correctly to the REST call.  When the cli is run however, no outputs are created.  It's possible I'm not entering values that make any sense, but I don't see any errors.

I can look into it more if someone gives me an example that should produce correct output.

### CODE REVIEW

**Comment by neal-siekierski** [comment]
By combining this with #44, I can get this to work for `PositivePixelCount`.

**Comment by jbeezley** [comment]
I updated this PR to add an icon to the job list widget that will display the contents of the output parameter file in a modal dialog.  I had to push additional information to the job model to get it to work, so it will only show up for newly run jobs.  @neal-siekierski perhaps you can give it a try and see if it works for you.

**Comment by neal-siekierski** [comment]
It indeed works as described. Great! A couple observations:
- If I delete the output file, I get a generic "An error occurred while communicating with the server" notification when I click on the icon.
- I can't select the displayed text to copy and paste it, which strikes me as a reasonable action to want to take.

**Comment by neal-siekierski** [comment]
Not showing on deletion works for me, but selectability doesn't. With Firefox 53, the `<pre class="s-output-parameters">` element with the output text ends up with the style `user-select: auto;`, but it reports the property value as being invalid.

**Comment by jbeezley** [comment]
The selection bug is actually more of a problem with HistomicsTK than this plugin.  We set to `user-select: none` on the top level element to avoid the issue documented at https://github.com/OpenGeoscience/geojs/issues/691.  We should avoid setting that property on modal dialogs.  I'll see if I can work around the firefox issue here.

**Comment by neal-siekierski** [comment]
Works for me.

**Comment by manthey** [comment]
@jbeezley Can you merge master?  The build should pass then.

**Pull request merged**
