### PR TITLE
Girder 2 support

### PR DESCRIPTION
**Pull request by jbeezley**
I think this is ready for review/merge.

### CODE REVIEW

**Comment by zachmullen** [comment]
This is good to go from my perspective.

**Comment by jbeezley** [comment]
I guess I'll add `npm-install-retry` here...

**Comment by jcfr** [comment]
@fedorov FYI The slicer_cli_web plugin is being updated to work with girder 2.x.

**Comment by jbeezley** [comment]
The docker tests seem to be [failing](https://travis-ci.org/girder/slicer_cli_web/builds/190708492#L1952) frequently.  @manthey Have you seen this before?

**Comment by manthey** [comment]
This happens when docker hub is slow to respond (or its download bandwidth is small).

We really need a petite docker image for testing.

**Comment by zachmullen** [comment]
Would it be worth trying to mock docker, or is this important as an integration test?

**Comment by manthey** [comment]
@jbeezley I made a small docker image on PR #24.  Merging that in will make testing faster.

Also, I think when this PR get merged in, we should make a branch called girder-1.7 so that applications that aren't Girder 2 ready have an obvious branch to use.

**Comment by jbeezley** [comment]
I created a girder-1.7 branch for backporting fixes.

**Comment by manthey** [comment]
Thanks.

**Pull request merged**
