### PR TITLE
Fix a bug where the client was parsing some XML REST responses as JSON

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by manthey** [comment]
The tests are failing due to issues that are fixed in commit @4e8624478b8349f867b2b80f379299d0a4ee21db (which is part of PR #23).  Just cherry-pick that commit into this branch so that the tests can pass.

It would be nice to have a simple test for this.

**Comment by brianhelba** [comment]
@manthey I'm not very familiar with what the client-side tests in this repo are doing. What would you like the test to do, more specifically?

**Comment by manthey** [comment]
@brianhelba I was just hoping for a test that would fail before the change and succeed after.  The plugin_tests/client/widget.js file references the panelGroup, but it looks like there aren't any tests of that component yet.

We can put off tests for now (as this whole repo needs more tests, which now I think should wait until after the Girder 2 change).  Can you cherry-pick the changes to the .travis.yml file so that the current tests pass, at which point I'll approve the PR?

**Comment by brianhelba** [comment]
Rebased.

**Comment by jcfr** [comment]
Thanks @manthey and @brianhelba for fixing the issue :+1:

**Pull request merged**
