### PR TITLE
Pull Image and use Image Digest

### LINKED ISSUE #74: Pull docker images to girder worker if not present
When we import a docker image, if the specified image is not present, we pull it to the Girder machine so we can query the cli.  However, since Girder Worker could be on a different machine, the image isn't necessarily present there.  When the task is run, if the image is not present, we should pull it on Girder Worker.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #74 

notes: 
 * in order to use the proper image digest, you have to reimport the image. 
 * there is no repo digest for local images (such as a locally built small-docker)

### CODE REVIEW

**Comment by manthey** [comment]
If I import a local docker image that has a different version on Docker hub, this doesn't work as expected.  My local docker image is not a version on Docker hub; I have it on both the Girder and Girder Worker dockers.  When I run the task, girder worker pulls down the Docker hub version (and the has failed with "WARNING: Container is still running, unable to remove.", but I haven't checked if that is strictly related).

**Comment by sgratzl** [comment]
I deactivated to explicitly pull the image. Docker should attempt to pull the image anyhow when running `docker run` and the image is not available yet

**Comment by manthey** [comment]
On loading and image and replacing an existing image, the digest needs to be cleared if it isn't available.  Specifically, I imported an image from docker hub.  I then imported an image of the same name from a local image, and the digest is still present.

**Comment by manthey** [comment]
When girder worker doesn't have the image, I still get `ImageNotFound: 404 Client Error: Not Found ("no such image: dsarchive/histomicstk@sha256:c7ccefe3c85eb3d60203862bdafb2393a8c39807e15e0248165cd02fa8463895: No such image: dsarchive/histomicstk@sha256:c7ccefe3c85eb3d60203862bdafb2393a8c39807e15e0248165cd02fa8463895")`

**Comment by sgratzl** [comment]
I added a simple logic to pull the image if it is not present. can you please test it again, since I don't have multiple docker setups

**Comment by manthey** [comment]
I'm not sure if this is strictly relevant to this branch, but I still have one test case that is failing.

girder_worker and girder are on the same system.   I import dsarchive/histomicstk:latest from docker hub.  I run a task.  I import a local version of dsarchive/histomicstk:latest (which updates the items).  When I run a task, I get "WARNING: Container is still running, unable to remove."; a container running my local version is left running (and the task fails to complete successfully). 

The local docker can be loaded via "docker load <tar file>", where the tar file is here: https://data.kitware.com/#item/5dbc7009e3566bda4b4f09c7

**Comment by manthey** [comment]
I can still get the error; it doesn't happen all of the time.

**Comment by manthey** [comment]
I'm wondering if it is this issue: https://github.com/celery/celery/issues/4867

**Pull request merged**
